#!/bin/bash

while getopts i: options; do
   case ${options} in
      i) ID=${OPTARG} ;;
   esac
done

declare -a RESPONSE=()

if ! [ -v JQ ] ; then
  RESPONSE+=("Export: Specifies the JQ.")
fi

if ! [ -v CURL ] ; then
  RESPONSE+=("Export: Specifies the CURL.")
fi

if ! [ -v ID ] ; then
  RESPONSE+=("-i: Specifies the id of planner.")
fi

if [ ${#RESPONSE[@]} -ne 0 ] ; then
  printf '%s\n' "${RESPONSE[@]}"
  exit 1;
fi

unset RESPONSE
