#!/bin/bash

source $TOOL/argument "$@"

AUTHORIZATION=$($CURL -k -s -X POST -F "email=$ENVIRONMENT_PLANNER_USERNAME" -F "password=$ENVIRONMENT_PLANNER_PASSWORD" https://login.energia-europa.com/api/iam/user/login | $JQ -r .authorization)
RESPONSE=$($CURL -k -s -X POST -H "x-authorization: $AUTHORIZATION" "$ENVIRONMENT_PLANNER_APIXSEND/$ID" | $JQ -rc .)
STATUS=$($JQ -rc .status <<< $RESPONSE)
[[ $STATUS != true ]] && exit 0

EMAIL=$($JQ -rc .email <<< $RESPONSE)
if [ $EMAIL != true ] ; then
    echo "The report $ID not send to recipient.";
    exit 1
fi

echo "The report $ID sended successful."
exit 0
